version: '3'
services:
  mysql:
    image: mysql:8
    container_name: qa-mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: qwerdfb
    volumes:
      - /tmp/qa/mysql/data:/var/lib/mysql
  redis:
    image: redis:6
    container_name: qa-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - /tmp/qa/redis/data:/data
  qa:
    container_name: qa
    build: .
    depends_on:
      - mysql
      - redis
    environment:
      - MYSQL_URL=root:qwerdfb@tcp(mysql:3306)/qa?charset=utf8mb4&parseTime=True&loc=Local
      - REDIS_URL=redis://redis:6379/0
    ports:
      - 8000:8000





  nebula-metad:
    image: vesoft/nebula-metad:v3.0.0
    volumes:
      - metad-data:/var/lib/nebula
    command: >
      nebula-metad --port 9559
      --meta_server_ports 9559
      --ws_ip 0.0.0.0
      --ws_port 19559
      --data_path /var/lib/nebula
      --local_ip ${HOST_IP}
    networks:
      nebula-net:

  nebula-graphd:
    image: vesoft/nebula-graphd:v3.0.0
    volumes:
      - graphd-data:/var/lib/nebula
    command: >
      nebula-graphd --port 3699
      --meta_server_addrs metad:9559
      --ws_ip 0.0.0.0
      --ws_port 19559
      --data_path /var/lib/nebula
      --bad_data_files_threshold 2
      --max_partition_num 1024
    depends_on:
      - nebula-metad
    networks:
      nebula-net:

  nebula-storaged:
    image: vesoft/nebula-storaged:v3.0.0
    volumes:
      - storaged-data:/var/lib/nebula
    command: >
      nebula-storaged --port 9779
      --meta_server_addrs metad:9559
      --data_path /var/lib/nebula
      --bad_data_files_threshold 2
      -- RocksDB.min_wal_size "1048576"
      -- RocksDB.max_wal_size "10485760"
    depends_on:
      - nebula-metad
    networks:
      nebula-net:

volumes:
  metad-data:
  graphd-data:
  storaged-data:

networks:
  nebula-net:
    driver: bridge